version: "3"
services:
  app:
    image: timers-image:latest
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql-container
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=my_database
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=my_database
  redis:
    image: redis:latest
