services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: timersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  redis:
    image: redis:latest
    container_name: myrediscontainer
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - internalnet

  nodeapp:
    depends_on:
      - mysqldb
      - redis
    container_name: mynodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      PORT: 3000
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: "admin"
      DB_PASSWORD: "letmein"
      DB_NAME: timersdb
      DB_CONNECTION_LIMIT: 100
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD:
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
